### ISSUE TITLE
无法编译DEMO

### ISSUE THREAD

**Issue by irelia97** [KiwanoEngine/Kiwano#71]
### 简述

使用NuGet安装了Kiwano包。然后编译用户手册中的[快速上手代码]，提示“无法解析外部符号”。不是很熟悉VS上的逻辑，安装好包后是否还要手动配置路径并指定要链接的库？

---------------

测试了下x86环境下能编，x64不行。这是特性还是Bug？

### 环境

1.2.26，Win11，VS2022

**Comment by nomango** [comment]
暂时限制了x64编译，有一个三方库只有x86版本，有时间了再改一下

**Comment by nomango** [comment]
resolved by #74
