### ISSUE TITLE
节点的拷贝构造函数

### ISSUE THREAD

**Issue by nomango** [KiwanoEngine/Kiwano#8]
应禁止一部分类的克隆功能，但是现在允许从拷贝构造函数创建新对象：

```cpp
auto node1 = new Node();
auto node2 = new Node(*node1);
```

如果对象中有指针类型的成员，这么拷贝出的对象就有很大的隐患

**Comment by Nomango** [comment]
resolve https://github.com/Nomango/Easy2D/commit/de951eaa40aaa34e724a911fe8b35ff3d2d1765e

**Comment by nomango** [comment]
resolve https://github.com/Nomango/Easy2D/commit/de951eaa40aaa34e724a911fe8b35ff3d2d1765e
